# Generated by Django 2.2.16 on 2020-09-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=900)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
